### ISSUE TITLE
index.html - Carousel entry for discord server is super long

### ISSUE THREAD

**Issue by shimutan** [shimutan/udip_website#78]
See attached image. When the carousel rotates to the Physics Discord entry, it gets significantly longer. Please adjust so that it is a similar length to the UDIP Project list.

![image](https://user-images.githubusercontent.com/72668942/135782800-505b76a4-4d8c-45c0-9256-8a4cdb79c11e.png)

![image](https://user-images.githubusercontent.com/72668942/135782873-588bf79f-3e9f-4c02-bc97-b8b5a0e66855.png)

**Comment by rufflehuffle** [comment]
Hi Ray,

My local copy of the website does not have this problem.

It seems that the live version of the website (on https://web.physics.ucsb.edu/~udip/index.html) does not have the updated **index.css** file. Going into the Chrome developer tools and checking the Sources tab confirms this.

So I'm thinking that this is a problem with the files not being properly updated.

For reference, here are the relevant lines of CSS and screenshots of the issue:

# Relevant lines of CSS
## Local Ver. (index.css | Lines 42 - 56)
```
/* xs screen size */
@media only screen and (max-width: 600px) {
  .card-columns{
    column-count: 1;
  }

  .carousel-img {
    width: 100%;
    height: 30vh;
  }

  #content-main {
    padding: 2rem 0 2rem 0;
  }
}
```

## Live Ver. (index.css | Lines 32-37)
```
/* xs screen size */
@media (max-width: 576px) {
  .card-columns{
    column-count: 1;
  }
}
```

# Local Version
![image](https://user-images.githubusercontent.com/25063058/135797484-4870357f-6eec-4103-a80b-af6669996e83.png)
# Live Version
![image](https://user-images.githubusercontent.com/25063058/135797502-66abfefa-00ad-408b-9e15-51a2518075cd.png)
